
from playwright.sync_api import sync_playwright

def run(playwright):
    browser = playwright.chromium.launch(headless=True)
    context = browser.new_context()
    page = context.new_page()

    # Use localhost server
    base_url = "http://localhost:8080"

    # 1. Verify Gallery
    print("Navigating to Gallery...")
    gallery_url = f"{base_url}/pages/prompt_gallery/index.html"
    print(f"Loading Gallery: {gallery_url}")

    try:
        page.goto(gallery_url)
        # Wait for static cards to load (they are generated by JS)
        page.wait_for_selector(".gallery-card", timeout=10000)
        print("Gallery cards found.")
        page.screenshot(path="verification/gallery_screenshot.png", full_page=True)
    except Exception as e:
        print(f"Gallery load failed: {e}")
        page.screenshot(path="verification/gallery_error.png", full_page=True)

    # 2. Verify Dashboard
    print("Navigating to Dashboard...")
    dashboard_url = f"{base_url}/dashboard.html"
    print(f"Loading Dashboard: {dashboard_url}")

    try:
        page.goto(dashboard_url)
        # Expect redirect to index.html or empty state if auth mock fails
        page.wait_for_load_state('networkidle')
        print(f"Current URL: {page.url}")
        page.screenshot(path="verification/dashboard_screenshot.png", full_page=True)
    except Exception as e:
         print(f"Dashboard load failed: {e}")
         page.screenshot(path="verification/dashboard_error.png", full_page=True)

    browser.close()

with sync_playwright() as playwright:
    run(playwright)
